name:                mksense
version:             0.2.0.0
github:              "VipeOut23/mksense"
license:             MIT
author:              "Jonas Röger"
maintainer:          "mail@jroeger.de"
copyright:           "2019 Jonas Röger"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/VipeOut23/mksense#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  mksense:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mksense

tests:
  mksense-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mksense
